Repository redBorder/redborder-cli, pull requests merged in 2024-05, with the labels that each got.

#15 Feature/add rpm build with GitHub actions
  .github/rpm.yml
  VERSION
Labels: size/M, build, kind/feature

#17 Add setup wizard option to red
  resources/lib/setup.rb
Labels: enhancement, size/S, kind/feature

#14 Improvements/handle errors on get chef node
  resources/lib/memcached.rb
  resources/lib/service.rb
  resources/lib/utils.rb
Labels: enhancement, kind/bug, size/M

#18 Release 0.0.15
  VERSION
  resources/lib/memcached.rb
  resources/lib/service.rb
  resources/lib/setup.rb
  resources/lib/utils.rb
Labels: enhancement, size/M, kind/documentation

#20 Improvement/old school services list
  resources/lib/service.rb
Labels: enhancement, size/M, kind/documentation

#21 Release 0.1.0
  VERSION
  resources/lib/service.rb
Labels: size/M, kind/documentation

#22 Add runtime to red service list
  resources/lib/service.rb
Labels: enhancement, size/M, kind/feature

#23 Release 0.1.1
  VERSION
  resources/lib/service.rb
Labels: size/M, kind/documentation

#19 Improvement/rename red to rbcli
  packaging/rpm/redborder-cli.spec
  resources/lib/memcached.rb
  resources/lib/zookeeper.rb
  resources/rbcli_bash_completion
  resources/scripts/rbcli.rb
Labels: enhancement, size/M, kind/feature

#24 Add -n or --no-color option to service list
  resources/lib/service.rb
Labels: enhancement, size/S, kind/feature

#25 Release 1.0.0
  VERSION
  packaging/rpm/redborder-cli.spec
  resources/lib/memcached.rb
  resources/lib/service.rb
  resources/lib/zookeeper.rb
  resources/rbcli_bash_completion
  resources/scripts/rbcli.rb
Labels: enhancement, size/M, kind/documentation
